### ISSUE TITLE
Broken link at CIP process

### ISSUE THREAD

**Issue by thiago-tsnnst** [cardano-foundation/developer-portal#689]
https://developers.cardano.org/docs/get-started/technical-concepts/#cardano-improvement-proposals-cip

Broken link
https://developers.cardano.org/docs/governance/cardano-improvement-proposals/CIP-0001

Should be replaced by this:
https://developers.cardano.org/docs/get-started/governance/cardano-improvement-proposals/CIP-0001

**Comment by thenic95** [comment]
Issue only appears on main branch in staging it's already fixed.

https://staging-dev-portal.netlify.app/docs/get-started/technical-concepts

@fill-the-fill when we push staging to main this should be fixed, correct?

**Comment by fill-the-fill** [comment]
I've made a PR to fix this issue

**Comment by thiago-tsnnst** [comment]
The problem still persist in the dev staging. 

https://staging-dev-portal.netlify.app/docs/get-started/governance/cardano-improvement-proposals/CIP-0001

**Comment by rphair** [comment]
Just noticed `CIP` in the title & verified that this indeed has been fixed.
