### ISSUE TITLE
Yarn Build task reports failure on timeout

### ISSUE THREAD

**Issue by rphair** [cardano-foundation/developer-portal#861]
Seen in my email immediately upon merging https://github.com/cardano-foundation/developer-portal/pull/860 (I'm the one who merged it):

#### Yarn Build: All jobs have failed

[View workflow run](https://github.com/cardano-foundation/developer-portal/actions/runs/3454272356)

The logs show it failed on a CIP download timeout, which we see happen all the time in local builds due to network glitches (at least I do in India); i.e. this was a rare and intermittent network problem to happen between GitHub's own servers.

If this needs to be solved, I think the solution for this would be to re-run the `yarn build` for a certain number of times before declaring a "failure".  Overall this seems easier than parsing the output to see if it failed on a CIP or other asset download.

cc @oversize

**Comment by oversize** [comment]
If the build is trying to download something as part of the build and the build did not succeed then the build rightfully so claims to have failed. But, i totaly get the false positive here. So, unfortunately i lack the rights to rerun jobs so maybe @katomm or @fickevics-makor can push that button for now? 

Going Forward i have two things in my mind: 1) Is it really needed to do the download in the build process or could these be done manually with a new commit? 2) If its needed (downloaded during the build), the code at ts/cip.ts should be fairly simple to adjust in the sense that it can catch the ETIMEDOUT exception thrown. Although, i am not a Typescript guy so my assumption may be wrong there.

**Comment by katomm** [comment]
Hello,
it looks like this was addressed already. Can anyone confirm?

**Comment by rphair** [comment]
@katomm the questions in https://github.com/cardano-foundation/developer-portal/issues/861#issuecomment-1313892638 have still not been answered, although the build failure reported above was only cosmetic (and temporary) since a properly tested PR was merged into `staging` anyway at the time this issue was raised.

**Comment by Mercurial** [comment]
We could also do a retry on the script level, I was the one who initially wrote the script 😅

**Comment by rphair** [comment]
Now that we know what to look for in the logs, and have established that any glitchy build failures are harmless, I feel we've done the due diligence to close this issue.  @Mercurial - empirically the low frequency & harmless nature of this error doesn't seem to justify any changes to the script behaviour.
